### ISSUE TITLE
Bricked

### ISSUE THREAD

**Issue by euphguy** [kendallgoto/switchbota#21]
Well I think I bricked one of my plugs. I set up the server and the dns redirect. I sent the Bluetooth code. It dropped off the network and never returned. 

Now the plug seems dead. No led. No response from the button or click from the relay. 

I may just return it unless you have any suggestions.

**Comment by kendallgoto** [comment]
did you look for a new wifi network after plugging it into the wall? if you're not familiar with tasmota: after the OTA process, the plugs don't rejoin your network automatically. They create a new network that you must connect to and repair it.

**Comment by euphguy** [comment]
I did, I do not see any new network. Tasmota or otherwise.

**Comment by kendallgoto** [comment]
That's disappointing to hear - sorry about that! Did you have other plugs that worked out?

The unfortunate part of OTAs like this is that if anything goes wrong, they're not recoverable & it's almost impossible to diagnose what went wrong.

Do you happen to have the logs from the Node server still? They should show a few requests from the device in the history.

**Comment by euphguy** [comment]
This was my first attempt. The plugs were a Prime Day impulse buy and an easy return. 

Thanks for the quick response!

**Comment by triggerx** [comment]
Keep trying euphguy.... I could have sworn I bricked one of mine, but I kept trying and it ended up working out perfectly.  Twice I had to use the bluetooth code, and one of those times I had to try several times, but like kendallgoto said, eventually I saw the Tasmota wifi AP magically come up.  Try again!
