### ISSUE TITLE
Operation has been verified on W2001401 (HomeKit JP Plug Mini)

### ISSUE THREAD

**Issue by hazi** [kendallgoto/switchbota#27]
Thank you for the great project.

I am an engineer using Plug mini in Japan.
I am happy to report that I got confirmation of the operation on W2001401 (HomeKit JP Plug Mini) today.

Setup was done according to the README.
No original settings were made.

Please let me know if there is anything I can do to help.

![image](https://user-images.githubusercontent.com/5656927/180652833-c326e9c3-ea7c-4a96-9641-8f8c5011aa43.png)
![image](https://user-images.githubusercontent.com/5656927/180652869-d98a2180-bdd7-4fc0-80a7-4a94e26c70f4.png)

**Comment by kendallgoto** [comment]
Thank you for sharing this! I haven't seen the Japanese models before. Glad they worked without difficulty.
