### ISSUE TITLE
Not an issue, just a happy user!

### ISSUE THREAD

**Issue by andiohn** [kendallgoto/switchbota#38]
This works so well. Congratulations! Sorry if this isn't the right place to do it.

I bought a 4-pack. They came with firmware 1.4, I set up the server and pushed the first bluetooth command. I went to the second one, and when I was done all 4; I pushed the second bluetooth command in order again. By the time I was back to the first one, it was showing the Tasmota SSID!

Worked so good. Thanks @kendallgoto!

**Comment by kendallgoto** [comment]
Thank you for the feedback. Glad it went well for you.
