### ISSUE TITLE
Cant get switchbota to work with switch on v1.2 firmware

### ISSUE THREAD

**Issue by triggerx** [kendallgoto/switchbota#4]
I have 3 plugs, two were on Firmware Version 1.1 and switchbota worked perfectly on those to upgrade to Tasmota.  However, the third one is on V1.2 and doesnt seem to be doing anything with the app.bin.  I can see the web server sending app.bin, so I can see it trying, but it's just not going.  Is this currently only working with Firmware Version 1.1?  Thanks.

**Comment by triggerx** [comment]
Your bluetooth instructions on the other issue worked brilliantly to resolve my issue!  3 for 3 now.  Thanks!

**Comment by handonam** [comment]
For reference, in case anyone was wondering to the above:

https://github.com/kendallgoto/switchbota/issues/3#issuecomment-1121864522
