### ISSUE TITLE
Reflashed app.bin to a device that already has tasmota running 

### ISSUE THREAD

**Issue by poxin13** [kendallgoto/switchbota#47]
Did something dumb and flashed two devices to the latest app.bin from the repo that already has tasmota running on them. Not getting an LED, wifi hotspot, or wifi connection now. Is there any hope in fixing these?

**Comment by kendallgoto** [comment]
i assume you got this resolved?

**Comment by poxin13** [comment]
I ended up disassembling the device and flashing it with the tasmota web installer
